# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpu_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gpu_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gpu_service.proto\x12\ngpusharing\"S\n\nTensorData\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x15\n\rrequires_grad\x18\x04 \x01(\x08\"W\n\tOpRequest\x12\x0f\n\x07op_name\x18\x01 \x01(\t\x12\x10\n\x08\x61rgs_pkl\x18\x02 \x01(\x0c\x12\'\n\x07tensors\x18\x03 \x03(\x0b\x32\x16.gpusharing.TensorData\"V\n\x08OpResult\x12\x12\n\nresult_pkl\x18\x01 \x01(\x0c\x12\'\n\x07tensors\x18\x02 \x03(\x0b\x32\x16.gpusharing.TensorData\x12\r\n\x05\x65rror\x18\x03 \x01(\t2F\n\nGPUService\x12\x38\n\tExecuteOp\x12\x15.gpusharing.OpRequest\x1a\x14.gpusharing.OpResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpu_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORDATA']._serialized_start=33
  _globals['_TENSORDATA']._serialized_end=116
  _globals['_OPREQUEST']._serialized_start=118
  _globals['_OPREQUEST']._serialized_end=205
  _globals['_OPRESULT']._serialized_start=207
  _globals['_OPRESULT']._serialized_end=293
  _globals['_GPUSERVICE']._serialized_start=295
  _globals['_GPUSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
